### ISSUE TITLE
ATC Information

### ISSUE THREAD

**Issue by MRJoos66** [tlewis17/MSFSTouchPortalPlugin#42]
I want to see the ATC Informations (e.g. Type=${value:MSFSTouchPortalPlugin.SimSystem.State.AtcType}). I use the event section of a button and it works very well. But it do not refresh until restart Touch Portal or this plugin. There is also no possibility to react to a change via an event, e.g. to automatically call up an individual page based on an aircraft type.

TouchPortal and Plugin are up to date

**Comment by TheRagingFury** [comment]
This plugin is fantastic THANK YOU. I would love to see some more features added if possible and open to incentivisation ideas/donating a bit maybe? List of additional possibilities is endless. I would love to see flap state and all the nav options. But I admit, I need to see if more can be done with keypress pass-ons. (although not sure that works so well)

**Comment by MRJoos66** [comment]
> This plugin is fantastic THANK YOU. I would love to see some more features added if possible and open to incentivisation ideas/donating a bit maybe? List of additional possibilities is endless. I would love to see flap state and all the nav options. But I admit, I need to see if more can be done with keypress pass-ons. (although not sure that works so well)

You have entered your contribution in the comments section of my question. However, that is not where it belongs. But I can still answer your question. There is the possibility to indicate the status of the flaps in percent.To do this, you have to go to the OnEvent area of a button. You have to enter the following. AddActions->Logic->DynamicTextUpdater and then in the text field e.g. "Flaps=" and then click on the plus symbol.  Then you have to select the following. 1) MSFSTouchportalPlugin 2) FlightSystem 3) FlapsHandlePercentage... Good luck and happy landings!

**Comment by TheRagingFury** [comment]
My apologies and thanks for the tip! will now delete it.

**Comment by mpaperno** [comment]
Re: ATC info and other strings not updating

I have been working on this plugin a bit and just ran into this problem myself.  It's an issue in the code, which I have fixed and will submit PR for shortly (among other things).  I also plan to publish a new version on my fork.  Will update soon.

**Comment by mpaperno** [comment]
I've published a test release with a fix for this, among a number of other changes.  Testers welcome!  ;-)

https://github.com/mpaperno/MSFSTouchPortalPlugin/releases

Updated [DOCUMENTATION](https://github.com/mpaperno/MSFSTouchPortalPlugin/blob/mp/main/DOCUMENTATION.MD)

**Comment by MRJoos66** [comment]
> I've published a test release with a fix for this, among a number of other changes. Testers welcome! ;-)
> 
> https://github.com/mpaperno/MSFSTouchPortalPlugin/releases
> 
> Updated [DOCUMENTATION](https://github.com/mpaperno/MSFSTouchPortalPlugin/blob/mp/main/DOCUMENTATION.MD)

Good news. I will test it tomorrow. I'm in the process of revising my TouchPortal pages anyway. This comes just at the right time :-)

**Comment by tlewis17** [comment]
> I've published a test release with a fix for this, among a number of other changes. Testers welcome! ;-)
> 
> https://github.com/mpaperno/MSFSTouchPortalPlugin/releases
> 
> Updated [DOCUMENTATION](https://github.com/mpaperno/MSFSTouchPortalPlugin/blob/mp/main/DOCUMENTATION.MD)

Nice work. Yeah the plugin was kind of put to the wayside due to RL commitments. How do you want to handle merging these PRs? The settings is one thing that was newer to Touch Portal that I hadn't gotten to working with yet. 

One improvement I was considering is that if you notice there is a lot of watching and transmitting of data to Touch Portal. I theorized that eventually it would be too much data and would cause performance issues. I was considering a way for the user to be able to enable what states they want to watch for, so they have control over that.

**Comment by mpaperno** [comment]
Hi Tim, good to hear from you.  Yeah RL happens... darn it!

We can discuss PRs on the PR comments, but in general I say merge them :-)  Or LMK what you'd like changed. If you merge the first 6 PRs then I can finalize the repeaters/settings one.  I've already made a few minor improvement tweaks, but it would be good to sync everything up first.

I'm also refactoring the action handling/mapping to allow for sending freeform action values to the sim (for Set/etc).  And less code.... ~330 lines of code removed just from `Engine.cs` alone.... :)

I may be throwing "a bunch" of PRs at you in the short term, as long as you're interested.  I can always just maintain my own fork, if you're not.  Also I just "learned" C# this week, so I'm sure there will be rookie style mistakes (me coming from lots of C/C++).

Cheers,
-Max

**Comment by tlewis17** [comment]
I merged all your PRs in to the release/1.0 branch. I like to use release branching and then when the release happens i merge that branch into master. Thanks for all those changes. It's great to have some help with this thing, it has grown way bigger than my own personal use project. 

I was attempting to work on G1000 soft keys on another branch and I have been unsuccessful with that. There is the possibility of having even more functions by incorporating Mobiflight into the program and using that API as well, which the G1000 soft keys were part of. Any changes to improve efficiency, scalability, or even just adding more states/actions is much appreciated.

**Comment by mpaperno** [comment]
Cool, thanks, glad you liked all that.  And you're welcome!  I'll check/rebase the last PR onto `!release` branch. And yes, a "feature merge" branch works well.

It's on my list to look at those PFD keys. Maybe they work since the new MSFS updates?  Would be nice to have.  My refactor of the actions makes it a bit easier to add new stuff and maintain the existing ones, so that should help. (just cut ~1K lines out of the Object definition files).  And I just recently discovered Mobi, but haven't played with that at all.  In my new action mapping scheme, the event names are stored as strings to begin with, so they don't have to be enum-friendly anymore (like for custom events with dots like `MobiFlight.AS1000_PFD_SOFTKEYS_1`).
